from config import Config

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
import re
import requests

from dotenv import load_dotenv

load_dotenv()

from database import save_blog, save_image_to_db
from prompts import templates

# LLM setup
llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    google_api_key=Config.GOOGLE_API_KEY
)

# Prompt
prompt = PromptTemplate(
    input_variables=["topic"],
    template=templates[0]
    )

# ✅ New LCEL chain
chain = prompt | llm


def generate_blog(topic):
    result = chain.invoke({"topic": topic})

    if hasattr(result, "content"):
        response = result.content
    else:
        response = result

    # ✅ If response is list → join it
    if isinstance(response, list):
        response = "".join(
            [r.get("text", "") if isinstance(r, dict) else str(r) for r in response]
        )

    # ✅ Now safe to clean
    html_content = response.replace("```html", "").replace("```", "").strip()

    # Extract title
    match = re.search(r"<h1>(.*?)</h1>", html_content, re.IGNORECASE)
    title = match.group(1) if match else topic

    html_content = re.sub(r"<h1>.*?</h1>", "", html_content, flags=re.IGNORECASE).strip()

    print(html_content)

    # html_content = inject_image_into_blog(html_content, topic)

    # save_blog(topic, title, html_content)

    return title, html_content


def get_pexels_image(topic):
    """
    Searches Pexels for a landscape photo matching the blog topic.
    Returns the image URL and its ALT text description.
    """
    url = "https://api.pexels.com/v1/search"
    headers = {
        "Authorization": Config.PIXEL_API_KEY
    }
    params = {
        "query": topic,
        "per_page": 1,
        "orientation": "landscape"
    }
    
    try:
        response = requests.get(url, headers=headers, params=params)
        response.raise_for_status()
        data = response.json()
        
        if data.get("photos"):
            photo = data["photos"][0]
            # 'large' or 'landscape' dimensions work best for blog headers (1200px+)
            image_url = photo["src"]["large"]
            alt_text = photo.get("alt") or f"Illustration for {topic}"
            return image_url, alt_text
            
    except requests.exceptions.RequestException as e:
        print(f"Pexels API Error: {e}")
        
    # Fallback default image in case search returns no results or fails
    fallback_url = "https://images.pexels.com/photos/262508/pexels-photo-262508.jpeg"
    return fallback_url, f"Blog cover for {topic}"


def inject_image_into_blog_and_save_image_to_db(raw_html, topic):
    """
    Fetches the image and injects its URL into the HTML generated by Gemini.
    """
    image_url, alt_text = get_pexels_image(topic)
    
    save_image_to_db(topic, image_url, alt_text)

    # 1. Replace the URL placeholder
    processed_html = raw_html.replace("https://placehold.co/800x400?text=Blog+Image", image_url)

    
    return processed_html